/**
 * Bridges DocuSign envelope events to Compliance__c.MSA_Status__c so the
 * EU indirect orchestration router can resume automatically once the merchant
 * (and Nuvei) sign the MSA generated by Track D.
 *
 * All logic lives in DocuSignStatusToMsa.handle() to keep the trigger thin
 * and unit-testable.
 */
trigger DocuSignStatusToMsaTrigger on dsfs__DocuSign_Status__c (after insert, after update) {
    DocuSignStatusToMsa.handle(Trigger.new, Trigger.oldMap);
}